db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: dp_dbname
  volumes:
    - ./docker-runtime/mysql:/var/lib/mysql
drupal:
  image: drupal:latest
  volumes:
    - ./:/var/www/
  links:
    - db:mysql
  ports:
    - 8080:80
